language: node_js
node_js:
  - "lts/*"

addons:
  apt:
    packages:
      - lcov

install:
  - npm install

script:
  - npm run test:coverage

after_success:
  - lcov --add-tracefile coverage/lcov.info | npm run coveralls
